#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAISendEmailOptions.h"
@protocol OAISendEmailOptions;
@class OAISendEmailOptions;



@protocol OAIBulkSendEmailOptions
@end

@interface OAIBulkSendEmailOptions : OAIObject

/* Inboxes to send from [optional]
 */
@property(nonatomic) NSArray<NSString*>* inboxIds;

@property(nonatomic) OAISendEmailOptions* sendEmailOptions;

@end
