#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBasicAuthOptions.h"
@protocol OAIBasicAuthOptions;
@class OAIBasicAuthOptions;



@protocol OAICreateWebhookOptions
@end

@interface OAICreateWebhookOptions : OAIObject


@property(nonatomic) OAIBasicAuthOptions* basicAuth;
/* Public URL (including protocol) that MailSlurp can post WebhookNotificationObjects to when an email is received [optional]
 */
@property(nonatomic) NSString* url;

@property(nonatomic) NSString* name;

@end
