#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIEmailAnalysis.h"
@protocol OAIEmailAnalysis;
@class OAIEmailAnalysis;



@protocol OAIEmail
@end

@interface OAIEmail : OAIObject


@property(nonatomic) OAIEmailAnalysis* analysis;

@property(nonatomic) NSArray<NSString*>* attachments;

@property(nonatomic) NSArray<NSString*>* bcc;

@property(nonatomic) NSString* body;

@property(nonatomic) NSArray<NSString*>* cc;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSString* from;

@property(nonatomic) NSDictionary<NSString*, NSString*>* headers;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* inboxId;

@property(nonatomic) NSString* rawUrl;

@property(nonatomic) NSString* subject;

@property(nonatomic) NSArray<NSString*>* to;

@property(nonatomic) NSDate* updatedAt;

@property(nonatomic) NSString* userId;

@end
