#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: d1659dc1567a5b62f65d0612107a50aace03e085
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIEmailAnalysis
@end

@interface OAIEmailAnalysis : OAIObject

/* Verdict of DomainKeys Identified Mail analysis [optional]
 */
@property(nonatomic) NSString* dkimVerdict;
/* Verdict of Domain-based Message Authentication Reporting and Conformance analysis [optional]
 */
@property(nonatomic) NSString* dmarcVerdict;
/* Verdict of spam ranking analysis [optional]
 */
@property(nonatomic) NSString* spamVerdict;
/* Verdict of Send Policy Framework record spoofing analysis [optional]
 */
@property(nonatomic) NSString* spfVerdict;
/* Verdict of virus scan analysis [optional]
 */
@property(nonatomic) NSString* virusVerdict;

@end
