#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInbox
@end

@interface OAIInbox : OAIObject


@property(nonatomic) NSDate* created;
/* The inbox's email address. Send an email to this address and the inbox will receive it [optional]
 */
@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* userId;

@end
