#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* ## Introduction  [MailSlurp](https://www.mailslurp.com) is an Email API for developers and QA testers. It let's users: - create emails addresses on demand - receive emails and attachments in code - send templated HTML emails  ## About  This page contains the REST API documentation for MailSlurp. All requests require API Key authentication passed as an `x-api-key` header.  Create an account to [get your free API Key](https://app.mailslurp.com/sign-up/).  ## Resources - 🔑 [Get API Key](https://app.mailslurp.com/sign-up/)                    - 🎓 [Developer Portal](https://www.mailslurp.com/docs/)           - 📦 [Library SDKs](https://www.mailslurp.com/docs/) - ✍️ [Code Examples](https://www.mailslurp.com/examples) - ⚠️ [Report an issue](https://drift.me/mailslurp)  ## Explore  
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInbox
@end

@interface OAIInbox : OAIObject


@property(nonatomic) NSDate* created;

@property(nonatomic) NSDate* createdAt;
/* Description of inbox [optional]
 */
@property(nonatomic) NSString* _description;
/* The inbox's email address. Send an email to this address and the inbox will receive it [optional]
 */
@property(nonatomic) NSString* emailAddress;
/* When if ever will the inbox expire [optional]
 */
@property(nonatomic) NSDate* expiresAt;
/* Is the inbox favourited [optional]
 */
@property(nonatomic) NSNumber* favourite;

@property(nonatomic) NSString* _id;
/* Name of inbox [optional]
 */
@property(nonatomic) NSString* name;
/* Tags that inbox has been tagged with [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;

@property(nonatomic) NSString* userId;

@end
