#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* ## Introduction  [MailSlurp](https://www.mailslurp.com) is an Email API for developers and QA testers. It let's users: - create emails addresses on demand - receive emails and attachments in code - send templated HTML emails  ## About  This page contains the REST API documentation for MailSlurp. All requests require API Key authentication passed as an `x-api-key` header.  Create an account to [get your free API Key](https://app.mailslurp.com/sign-up/).  ## Resources - 🔑 [Get API Key](https://app.mailslurp.com/sign-up/)                    - 🎓 [Developer Portal](https://www.mailslurp.com/docs/)           - 📦 [Library SDKs](https://www.mailslurp.com/docs/) - ✍️ [Code Examples](https://www.mailslurp.com/examples) - ⚠️ [Report an issue](https://drift.me/mailslurp)  ## Explore  
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIJsonNode
@end

@interface OAIJsonNode : OAIObject


@property(nonatomic) NSNumber* array;

@property(nonatomic) NSNumber* bigDecimal;

@property(nonatomic) NSNumber* bigInteger;

@property(nonatomic) NSNumber* binary;

@property(nonatomic) NSNumber* boolean;

@property(nonatomic) NSNumber* containerNode;

@property(nonatomic) NSNumber* _double;

@property(nonatomic) NSNumber* empty;

@property(nonatomic) NSNumber* _float;

@property(nonatomic) NSNumber* floatingPointNumber;

@property(nonatomic) NSNumber* _int;

@property(nonatomic) NSNumber* integralNumber;

@property(nonatomic) NSNumber* _long;

@property(nonatomic) NSNumber* missingNode;

@property(nonatomic) NSString* nodeType;

@property(nonatomic) NSNumber* null;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* object;

@property(nonatomic) NSNumber* pojo;

@property(nonatomic) NSNumber* _short;

@property(nonatomic) NSNumber* textual;

@property(nonatomic) NSNumber* valueNode;

@end
