#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIMatchOption
@end

@interface OAIMatchOption : OAIObject

/* The email property to match on. One of SUBJECT, TO, BCC, CC or FROM [optional]
 */
@property(nonatomic) NSString* field;
/* What criteria to apply. CONTAIN or EQUAL. Note CONTAIN is recommended due to some SMTP servers adding new lines [optional]
 */
@property(nonatomic) NSString* should;
/* The value to compare to the field using EQUAL or CONTAIN [optional]
 */
@property(nonatomic) NSString* value;

@end
