#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIEmailProjection.h"
#import "OAIPageable.h"
#import "OAISort.h"
@protocol OAIEmailProjection;
@class OAIEmailProjection;
@protocol OAIPageable;
@class OAIPageable;
@protocol OAISort;
@class OAISort;



@protocol OAIPageEmailProjection
@end

@interface OAIPageEmailProjection : OAIObject


@property(nonatomic) NSArray<OAIEmailProjection>* content;

@property(nonatomic) NSNumber* first;

@property(nonatomic) NSNumber* last;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* numberOfElements;

@property(nonatomic) OAIPageable* pageable;

@property(nonatomic) NSNumber* size;

@property(nonatomic) OAISort* sort;

@property(nonatomic) NSNumber* totalElements;

@property(nonatomic) NSNumber* totalPages;

@end
