#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* ## Introduction  [MailSlurp](https://www.mailslurp.com) is an Email API for developers and QA testers. It let's users: - create emails addresses on demand - receive emails and attachments in code - send templated HTML emails  ## About  This page contains the REST API documentation for MailSlurp. All requests require API Key authentication passed as an `x-api-key` header.  Create an account to [get your free API Key](https://app.mailslurp.com/sign-up/).  ## Resources - 🔑 [Get API Key](https://app.mailslurp.com/sign-up/)                    - 🎓 [Developer Portal](https://www.mailslurp.com/docs/)           - 📦 [Library SDKs](https://www.mailslurp.com/docs/) - ✍️ [Code Examples](https://www.mailslurp.com/examples) - ⚠️ [Report an issue](https://drift.me/mailslurp)  ## Explore  
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAISendEmailOptions
@end

@interface OAISendEmailOptions : OAIObject

/* Optional list of attachment IDs to send with this email. You must first upload each attachment separately in order to obtain attachment IDs [optional]
 */
@property(nonatomic) NSArray<NSString*>* attachments;
/* Optional list of bcc destination email addresses [optional]
 */
@property(nonatomic) NSArray<NSString*>* bcc;
/* Contents of email. If body contains HTML then set `isHTML` to true. You can use moustache template syntax in the body in conjunction with `toGroup` contact variables or `templateVariables` data. [optional]
 */
@property(nonatomic) NSString* body;
/* Optional list of cc destination email addresses [optional]
 */
@property(nonatomic) NSArray<NSString*>* cc;
/* Optional charset [optional]
 */
@property(nonatomic) NSString* charset;
/* Optional from address. If not set source inbox address will be used [optional]
 */
@property(nonatomic) NSString* from;
/* Optional HTML flag. If true the `content-type` of the email will be `text/html` [optional]
 */
@property(nonatomic) NSNumber* isHTML;
/* Optional replyTo header [optional]
 */
@property(nonatomic) NSString* replyTo;
/* Optional email subject line [optional]
 */
@property(nonatomic) NSString* subject;
/* Optional template ID to use for body. Will override body if provided [optional]
 */
@property(nonatomic) NSString* template;
/* Optional map of template variables. Will replace moustache syntax variables in subject and body or template with the associated values [optional]
 */
@property(nonatomic) NSObject* templateVariables;
/* List of destination email addresses. Even single recipients must be in array form. Max 100 recipients. [optional]
 */
@property(nonatomic) NSArray<NSString*>* to;
/* Optional list of contact IDs to send email to [optional]
 */
@property(nonatomic) NSArray<NSString*>* toContacts;
/* Optional contact group ID to send email to [optional]
 */
@property(nonatomic) NSString* toGroup;

@end
