#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAISendEmailOptions
@end

@interface OAISendEmailOptions : OAIObject

/* Optional list of attachment IDs to send with this email. You must first upload each attachment separately in order to obtain attachment IDs [optional]
 */
@property(nonatomic) NSArray<NSString*>* attachments;
/* Optional list of bcc destination email addresses [optional]
 */
@property(nonatomic) NSArray<NSString*>* bcc;
/* Contents of email. If HTML set isHTML to true. You can use moustache templates here if you provide a templateVariables option [optional]
 */
@property(nonatomic) NSString* body;
/* Optional list of cc destination email addresses [optional]
 */
@property(nonatomic) NSArray<NSString*>* cc;
/* Optional charset [optional]
 */
@property(nonatomic) NSString* charset;
/* Optional from address. If not set source inbox address will be used [optional]
 */
@property(nonatomic) NSString* from;

@property(nonatomic) NSNumber* html;
/* Optional replyTo header [optional]
 */
@property(nonatomic) NSString* replyTo;
/* Optional email subject line [optional]
 */
@property(nonatomic) NSString* subject;
/* Optional map of template variables. Will replace moustache syntax variables in subject or body with the associated values [optional]
 */
@property(nonatomic) NSObject* templateVariables;
/* List of destination email addresses. Even single recipients must be in array form. 
 */
@property(nonatomic) NSArray<NSString*>* to;

@end
