#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIMatchOption.h"
@protocol OAIMatchOption;
@class OAIMatchOption;



@protocol OAIWaitForConditions
@end

@interface OAIWaitForConditions : OAIObject

/* Number of results that should match conditions [optional]
 */
@property(nonatomic) NSNumber* count;
/* Should exactly count number of results be returned or at least that many. [optional]
 */
@property(nonatomic) NSString* countType;
/* Inbox to search within [optional]
 */
@property(nonatomic) NSString* inboxId;
/* Conditions that should be matched [optional]
 */
@property(nonatomic) NSArray<OAIMatchOption>* matches;
/* Direction to sort matching emails by created time [optional]
 */
@property(nonatomic) NSString* sortDirection;
/* Max time in milliseconds to wait until conditions are met [optional]
 */
@property(nonatomic) NSNumber* timeout;
/* Apply only to unread emails [optional]
 */
@property(nonatomic) NSNumber* unreadOnly;

@end
