#import <Foundation/Foundation.h>
#import "OAIBulkSendEmailOptions.h"
#import "OAIInbox.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIBulkActionsControllerApi: NSObject <OAIApi>

extern NSString* kOAIBulkActionsControllerApiErrorDomain;
extern NSInteger kOAIBulkActionsControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Bulk create Inboxes (email addresses)
/// 
///
/// @param count Number of inboxes to be created in bulk
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<OAIInbox>*
-(NSURLSessionTask*) bulkCreateInboxesWithCount: (NSNumber*) count
    completionHandler: (void (^)(NSArray<OAIInbox>* output, NSError* error)) handler;


/// Bulk Delete Inboxes
/// 
///
/// @param ids ids
/// 
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden"
///
/// @return void
-(NSURLSessionTask*) bulkDeleteInboxesWithIds: (NSArray<NSString*>*) ids
    completionHandler: (void (^)(NSError* error)) handler;


/// Bulk Send Emails
/// 
///
/// @param bulkSendEmailOptions bulkSendEmailOptions
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) bulkSendEmailsWithBulkSendEmailOptions: (OAIBulkSendEmailOptions*) bulkSendEmailOptions
    completionHandler: (void (^)(NSError* error)) handler;



@end
