#import <Foundation/Foundation.h>
#import "OAIEmail.h"
#import "OAIInbox.h"
#import "OAISendEmailOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
*
* OpenAPI spec version: 0.0.1-alpha
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAICommonOperationsApi: NSObject <OAIApi>

extern NSString* kOAICommonOperationsApiErrorDomain;
extern NSInteger kOAICommonOperationsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create new email address
/// Returns an Inbox with an `id` and an `emailAddress`
///
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return OAIInbox*
-(NSURLSessionTask*) createNewEmailAddressWithCompletionHandler: 
    (void (^)(OAIInbox* output, NSError* error)) handler;


/// Delete email address and its emails
/// Deletes an inbox
///
/// @param inboxId inboxId
/// 
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:410 message:"Gone"
///
/// @return void
-(NSURLSessionTask*) deleteEmailAddressWithInboxId: (NSString*) inboxId
    completionHandler: (void (^)(NSError* error)) handler;


/// Send an email from a random email address
/// To specify an email address first create an inbox and use that with the other send email methods
///
/// @param sendEmailOptions sendEmailOptions
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) sendEmailSimpleWithSendEmailOptions: (OAISendEmailOptions*) sendEmailOptions
    completionHandler: (void (^)(NSError* error)) handler;


/// Fetch inbox's latest email or if empty wait for email to arrive
/// Will return either the last received email or wait for an email to arrive and return that. If you need to wait for an email for a non-empty inbox see the other receive methods.
///
/// @param inboxEmailAddress Email address of the inbox we are fetching emails from (optional)
/// @param inboxId Id of the inbox we are fetching emails from (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return OAIEmail*
-(NSURLSessionTask*) waitForLatestEmailWithInboxEmailAddress: (NSString*) inboxEmailAddress
    inboxId: (NSString*) inboxId
    completionHandler: (void (^)(OAIEmail* output, NSError* error)) handler;


/// Wait for or fetch the email with a given index in the inbox specified
/// 
///
/// @param inboxId Id of the inbox we are fetching emails from (optional)
/// @param index Zero based index of the email to wait for (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return OAIEmail*
-(NSURLSessionTask*) waitForNthEmailWithInboxId: (NSString*) inboxId
    index: (NSNumber*) index
    completionHandler: (void (^)(OAIEmail* output, NSError* error)) handler;



@end
