#import <Foundation/Foundation.h>
#import "OAIDescribeDomainOptions.h"
#import "OAIDescribeMailServerDomainResult.h"
#import "OAIEmailVerificationResult.h"
#import "OAIVerifyEmailAddressOptions.h"
#import "OAIApi.h"

/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIMailServerControllerApi: NSObject <OAIApi>

extern NSString* kOAIMailServerControllerApiErrorDomain;
extern NSInteger kOAIMailServerControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get DNS Mail Server records for a domain
/// 
///
/// @param describeOptions describeOptions
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return OAIDescribeMailServerDomainResult*
-(NSURLSessionTask*) describeMailServerDomainWithDescribeOptions: (OAIDescribeDomainOptions*) describeOptions
    completionHandler: (void (^)(OAIDescribeMailServerDomainResult* output, NSError* error)) handler;


/// Verify the existence of an email address at a given mail server.
/// 
///
/// @param verifyOptions verifyOptions
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return OAIEmailVerificationResult*
-(NSURLSessionTask*) verifyEmailAddressWithVerifyOptions: (OAIVerifyEmailAddressOptions*) verifyOptions
    completionHandler: (void (^)(OAIEmailVerificationResult* output, NSError* error)) handler;



@end
